### ISSUE TITLE
Workflow for advanced EML files

### ISSUE THREAD

**Issue by dfalster** [ropensci/EML#107]
Hi @cboettig,

With help from @karen-ross, I have been preparing some datafiles to make public and trying to apply your REML package. I expect to do this somewhat often, so have tried to set up a worklow that

1. stored all key metatdata in files
2. uses these files to generate a standard readme file
3. uses the same files to generate an rich EML file (as per instructions [here](https://github.com/ropensci/EML/blob/devel/inst/doc/vignettes/Advanced_writing_of_EML.md).

My goal was to set it up so that I could get collaborators to give me information, put that into standard format, then squeeze out a readme and XML file. 

My first attempt at doing this is available here: [https://github.com/dfalster/Falster_2005_JEcol_data](https://github.com/dfalster/Falster_2005_JEcol_data)

It's mostly working but I have hit an error in generating the EML file, as described [here](https://github.com/dfalster/Falster_2005_JEcol_data/issues/2):

```
Error in as(i, "XMLInternalNode") : 
  no method or default for coercing “creator” to “XMLInternalNode”
```
 
I would appreciate any suggestions you have (feel free to clone, send PRs). Also, do let me know if you have any feedback on my approach for wrapping around your EML package.

with best regards,
Daniel

**Comment by cboettig** [comment]
I think most of these issues are now addressed in the new re-write of EML, which provides somewhat simpler constructors for using multiple creators, etc.  Some of this is illustrated in the new vignette.  

Note that the new version is not fully backwards-compatible with the old version, though much old EML code may still work.
