### ISSUE TITLE
Add a shiny module to write metadata

### ISSUE THREAD

**Issue by karthik** [ropensci/EML#116]
As discussed with @cboettig I'll push a shiny module that will make it easier to document metadata in a browser than use the command line wizard which can be painful to use if you don't know what option to use or want to document fields out of order.

**Comment by ivanhanigan** [comment]
I tried building such a thing using `web2py` interface to a shared `PostgreSQL` database (or `SQLite` if you are a sole trader). 
https://github.com/ivanhanigan/data_inventory

This is a relational DB with a table for `project`, `dataset`, `entity` info and links between `dataset` and `intellectualRights`.  Me and a team of data librarians were all concurrent users to the database, curating data on a file server for upload to metacat,  Postgres helped also manage custom fields like date data requested, date recieved, licence code, additional notes. And then once all prep work was done we would extract the elements to insert into EML, via morpho and upload to metacat.  This was less than optimal in many regards: the relational DB model allowed only one field for `creator`, `associatedParty`, etc.  `keywords` was a related table to dataset, but this was clunky...

I think `Shiny` with connection to `R/EML` helper functions is a better way to build EML, but just want to note that the other things in the RDMS like `date_requested` and `date_expected` were very useful to manage our workflow in the team that had to deal with a lot of associated information to do with data that is not strictly part of the `EML`.

**Comment by maelle** [comment]
Someone wants to develop such a thing, cf [the collaborative document](https://docs.google.com/document/d/1JiLJx_kM48JXqjiUiZh4cJEm5UNCfMnNijly40roS5w/edit)  for [this ecology hackathon](https://methodsblog.wordpress.com/2017/11/16/hackathon-challenges/)
