### ISSUE TITLE
Add tutorial on handling standard and custom units

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#120]
- [ ] provide numbered list to select a standard unit
- [ ] suggest standard unit based on partial name matching
- [ ] attempt matches against standard unit abbreviations
- [ ] Present options for a unitType from existing list
- [ ] prompt new unitType creation

**Comment by maelle** [comment]
I have a stupid unit question, I hope it's ok to ask it here. When defining an EML for several tables, there's only one custom unit list for the whole EML, not one by table, right?

**Comment by amoeba** [comment]
Yep. Each table needs to reference the custom unit but the unit is defined
in the additionalMetadata section. There is at least one example in the
inst dir of this package.

**Comment by maelle** [comment]
Thanks @amoeba !

**Comment by amoeba** [comment]
Example here https://github.com/ropensci/EML/blob/master/inst/xsd/test/eml-datasetWithUnits.xml

While I'm on this Issue, we've got some WIP EML documentation on our enterprise GH install that I think would be useful for the package and appropriate for this thread. I'll make myself a note to take  a look.

@cboettig Are some of these bullet items things you're still interested in having?

**Comment by cboettig** [comment]
Definitely, thanks

**Comment by cboettig** [comment]
closing in favor of #243
