### ISSUE TITLE
?write_eml typo

### ISSUE THREAD

**Issue by rBatt** [ropensci/EML#127]
https://github.com/ropensci/EML/blob/master/man/eml_write.Rd#L25

should be ?data.set, right?

**Comment by cboettig** [comment]
No, it's dataset.  See ?dataset.   We're deprecating the data.set idea,
which was a kind of extension of data.frame.

**Comment by rBatt** [comment]
I get an error when doing `?dataset`, but not for `?data.set`

**Comment by cboettig** [comment]
Ah good point; yeah, the docs are really incomplete right now.  dataset
passes most of these options down to the lower-level stucture 'dataTable'
anyhow, so you can see ?eml_dataTable. The 'writing EML' vignette might be
a bit better intro
https://github.com/ropensci/EML/blob/master/vignettes/Advanced_writing_of_EML.Rmd
for now, but lots of rough edges still
