### ISSUE TITLE
broken link to `Advanced writing of EML`

### ISSUE THREAD

**Issue by rBatt** [ropensci/EML#128]
The read me has a link to the following:

https://github.com/ropensci/EML/blob/master//vignettes/Advanced_writing_of_EML.md

But I think it's intended to go here:

https://github.com/ropensci/EML/blob/master/vignettes/Advanced_writing_of_EML.Rmd

2 characters off

**Comment by rBatt** [comment]
I only found the right page because of links in #127

**Comment by cboettig** [comment]
Issue deprecated by `eml2` 0009056630bb3215dcb26f54c46a725681602010.  new vignette to come.
