### ISSUE TITLE
example for creating additionalMetadata manually?

### ISSUE THREAD

**Issue by rBatt** [ropensci/EML#130]
I'm unsure of how to get some of the formatting correct. Thus far I've relied on the S4 classes and filling slots, or using the helpful functions.

for the additionalMetadata, the `metadata` slot doesn't really provide much help, I don't think.

In particular, how am I supposed to enter tags?

```R
An object of class "ListOfadditionalMetadata"
[[1]]
An object of class "additionalMetadata"
Slot "describes":
character(0)

Slot "id":
character(0)

Slot "metadata":
<metadata>
  <additionalClassifications>
    <status>ongoing</status>
    <researchTopic>community</researchTopic>
    <studyType>short-term measurement</studyType>
    <studyType>modeling</studyType>
  </additionalClassifications>
</metadata> 


[[2]]
An object of class "additionalMetadata"
Slot "describes":
character(0)

Slot "id":
character(0)

Slot "metadata":
<metadata>
  <additionalLinks>
    <url name="Ecophysiology of Carnivorous Plants Worldwide 1980-2011">http://harvardforest.fas.harvard.edu:8080/exist/xquery/data.xq?id=hf168</url>
    <url name="Effects of Prey Availability on Sarracenia Physiology at Harvard Forest 2005">http://harvardforest.fas.harvard.edu:8080/exist/xquery/data.xq?id=hf109</url>
    <url name="Food Web of Sarracenia Purpurea in United States and Canada since 1999">http://harvardforest.fas.harvard.edu:8080/exist/xquery/data.xq?id=hf193</url>
    <url name="Thresholds and Regime Shifts at Four LTER Sites (CCE, JRN, PAL, SBC) 1951-2009">http://harvardforest.fas.harvard.edu:8080/exist/xquery/data.xq?id=hf170</url>
    <url name="Nitrogen Cycling Dynamics in Sarracenia Purpurea at Harvard Forest 2004-2005">http://harvardforest.fas.harvard.edu:8080/exist/xquery/data.xq?id=hf096</url>
    <url name="Organic and Inorganic Nitrogen Uptake by Sarracenia Purpurea at Harvard Forest and Fort Albany ON 2007">http://harvardforest.fas.harvard.edu:8080/exist/xquery/data.xq?id=hf146</url>
    <url name="Prey Capture by Carnivorous Plants Worldwide 1923-2007">http://harvardforest.fas.harvard.edu:8080/exist/xquery/data.xq?id=hf111</url>
    <url name="Sarracenia Purpurea Prey Capture at Harvard Forest 2008">http://harvardforest.fas.harvard.edu:8080/exist/xquery/data.xq?id=hf114</url>
    <url name="Allochthonous Nutrients in the Sarracenia Microecosystem at Harvard Forest 2005-2007">http://harvardforest.fas.harvard.edu:8080/exist/xquery/data.xq?id=hf098</url>
  </additionalLinks>
</metadata>

```

How am I supposed to write that manually?

**Comment by cboettig** [comment]
It isn't really expected that users will write additionalMetadata nodes
manually.  Rather, metadata in this section may be generated by various
other automated utilities when an appropriate field does not already exist.

Can you let me know a bit more about what you mean by tags?  If you are
looking for keywords, there the eml_keyword function that is shown in the
'advanced writing' vignette.

@mbjones can correct me but I'm not sure that having additionalLinks in the
additionalMetadata section as in that Harvard forest example is really the
best/correct structure for providing a list of additional links.  @mbjones
thoughts?

**Comment by mbjones** [comment]
@cboettig Well, it depends if there is a standard field where that information belongs.  For example, if these are taxonomic references that help define the taxonomy used in the data, then they should probably be listed in the [`classificationSystemCitation` field](https://knb.ecoinformatics.org/#external//emlparser/docs/eml-2.1.1/./eml-coverage.html#classificationSystemCitation).  But, if there is no appropriate location for them in the main EML document, then `additionalMetadata` is the appropriate place.

**Comment by rBatt** [comment]
@cboettig by "tags" I meant `<additionalLinks> </additionalLinks>`, etc. I.e., HTML tags (that's what they look like to me).

As I'm learning more about the standard fields in EML, I'm able to find homes for the information I have. That's great. However, there are some things that just aren't easily included.

For example, describing the crossed/nested structure of columns, whether something like "weight per unit effort" accounts for changes in gear, and what methodological approaches were consistent in sampling (beyond what's stated in the units). Like I said, I think a lot of this might go into the methods field (still figuring some of this out), but I'm anticipating important bits of information that might require new fields or just ad hoc chunks of text.

For now, I have website pages I want to link to.
