### ISSUE TITLE
Typo related to vexatious issue of 'wide' data

### ISSUE THREAD

**Issue by ivanhanigan** [ropensci/EML#134]
As described in pull request #126,  [https://github.com/ropensci/EML/blame/master/manuscripts/one-simple-way.Rmd#L234](https://github.com/ropensci/EML/blame/master/manuscripts/one-simple-way.Rmd#L234)  I believe there is a typo in this section and you mean to say 'observations for a single site added as additional columns' rather than 'rows' as it currently reads.

**Comment by cboettig** [comment]
Hadley's "tidy data" concept, which is essentially based on "[Codd's third normal form](https://en.wikipedia.org/wiki/Third_normal_form)", states that additional observations should always be rows, while additional variables should be columns.  While I still believe this is generally a good idea, and has gotten easier to accomplish in R thanks to packages like `tidyr` and `dplyr`, I also now feel that it was a bit of an overreach to bring this issue up in the EML R package, which should probably just aim at just writing the EML for the data it is given without any fuss over best practices issues.

I'll take a look at the PR and see if I can follow your issue better; thanks for revisiting this.  But for this issue, I think the language is correct; but we will probably scrap the draft you link anyway and try and move forward with more practical / less opinionated documentation.

**Comment by ivanhanigan** [comment]
Thanks for your comments.  I agree.  Perhaps the words can still be used somewhere, but I suggest slight re-phrasing such as:
```
Partly because this format may require duplicated entries, such as 
repeating the value of the "site" when multiple observations have been 
made on the same site, many researchers  
prefer to present data in "wide" format, with new observations for a single 
site added as additional columns as they find this more convenient for field entry.
Whilst we agree with Wickham etc that the long format is more desirable for
most future analysis or reuse, the EML package just aims to help writing the
metadata for the data as given, without being opinionated over best practices issues.
```

Thanks again!
