### ISSUE TITLE
eml_read() error while parsing content

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/EML#136]
Reading a remote file produces the following error:

```
> library(EML)
> obj <- eml_read("https://mn-stage-ucsb-2.test.dataone.org/knb/d1/mn/v2/object/testV1CreateV2ListObjects_2015337133715794")
No encoding supplied: defaulting to UTF-8.
Error in UseMethod("xmlRoot") : 
  no applicable method for 'xmlRoot' applied to an object of class "c('xml_document', 'xml_node')"
> obj
Error: object 'obj' not found
```

This error occurs with version httr_1.1.0, when content(GET(file), "parsed") returns xml2::xml_document.
One solution is to return text, i.e. content(..., as="text") and parse the document manually.

**Comment by cboettig** [comment]
thanks.  Just a heads up, this EML implementation really isn't schema-complete and I'm working on a replacement I hope to have functional soon: https://github.com/cboettig/eml2/issues/1

**Comment by cboettig** [comment]
Merged `eml2` into `EML` master branch.  `eml_read()` logic is simpler and no longer supports reading directly from a network connection, but offers a much smaller dependency footprint as a result.  Users can download file first however they prefer; while eml_read()'s behaviour is more predictably aligned with xmlParse.
