### ISSUE TITLE
Documenting Methods & other long-format textType: Docbook vs EML conventions

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#137]
Looking for feedback from @mbjones and others on the best interface for handling the creation of long-form text in EML documents.  In particular, I might need some clarification from @mbjones on what part of Docbook EML does and doesn't support.

My proposal here is that the author would write long-form documentation, such as a `<methods>` section, in one or more markdown files.  This is more natural than writing lots of text in a code file, and markdown is increasingly familiar to and well integrated with R.  In particular, thanks to `rmarkdown` and RStudio's shipping with pandoc built in, we have an easy and automatic way to transform this markdown into Docbook, which a user could then drop in to the appropriate EML slots.

Note that pandoc now uses `<sect1>` etc elements instead of `<section>` elements (see [this thread](https://groups.google.com/forum/#!topic/pandoc-discuss/kMwuoj48k_M), apparently this is consistent with O'Reilly requirements and more common now?). 

EML documents having `section` and `para` elements in TextType fields.  Currently the S4 class define the text slots down to a list of `section` and `para` classes, which take pure XML after that to avoid needless back-and-forth conversion, so we can map all the `<sectN><para> ...` to `new("section", para = ....)` on the back end.  The user interface would just be something like 

```r
methods <- set_methods("path/to/methods.md")
```
which would return a valid S4 `methods` object.  Does this sound reasonable (from both user and developer perspective)?  How likely is it that we end up with invalid EML when we just allow the pandoc docbook converter to generate arbitrary docbook text from a markdown document?

**Comment by ivanhanigan** [comment]
I'm interested in this change in direction.
Back in the day
https://github.com/ivanhanigan/EML/blame/master/vignettes/Advanced_writing_of_EML.Rmd#L288
used Word docs.
I worked with field ecologists and we got lots of documentation in Word.  I
was thinking that approach would be easiest (ie how many are going to start
using markdown?).
I also started suspecting that a couple tables in a word document might
ensure consistent data entry.  then read in to dataframes using
https://github.com/hrbrmstr/docxtractr
maybe a table for project-module tags, another for dataset-module, another
for entities....
(but this would then limit the use of non-relational data structures and
repeated elements like multiple associatedParties etc)


Just my 2cents worth, to keep the energy levels high (I really want this
package)

Ta

**Comment by cboettig** [comment]
@ivanhanigan thanks much!  You're definitely right, we should support Word for this as well.  Fortunately, pandoc makes this easy, since we should be able to offer any pandoc input format, including Word, to transform into Docbook and then into EML.

**Comment by cboettig** [comment]
@ivanhanigan The new vignette shows importing from Word (`.docx`) into a methods element.

@mbjones Could use your advice here.  It appears that some things that are valid DocBook formats are not valid EML (as you probably already know).  I'm just not sure how best to address that.  For instance, if I put in an ordered list or boldface in a markdown file and let pandoc convert that to docbook, the resulting docbook `section`s are not valid EML.  As long as the formatting is kept pretty simple, this strategy works fine though (see examples in the new vignette draft, #145.  I really think it would be great to be able to leverage the pandoc conversion capacity here.  

As a side note, I've made `rmarkdown`/pandoc a "suggested" package instead of an imported one.  Since RStudio ships with `pandoc` I think this approach should now be accessible to most users, but for users wanting to install the package on a platform where `pandoc` isn't readily available that added dependency can be a huge pain (particularly since a simple `install.packages` won't resolve the problem).  So I've followed the tricks used in in `ggplot2` and put in an error message about installing `rmarkdown` if it is not available.  

Users without pandoc installed can still provide an external file that has already been converted to docbook/xml (`.dbk` or `.xml` extension) (possibly with some other tool, since lots of tools can create docbook) and the `set_methods()` and `set_section()` function will use that directly.

**Comment by mbjones** [comment]
@cboettig For various reasons and after extensive debate, the EML community decided to only allow a limited subset of markup in TextType sections, and decided to make this markup correspond to their docbook counterparts.  It is not, technically, docbook.  One could argue, and several people did, that any docbook should be legal in TextType.  But, docbook is an extensive language, and that would introduce significant processing issues for implementers and editors.  At the time EML was written, tools like pandoc did not yet exist, and so dealing with this markup wa sdeemed to be too burdensome. If you think this should be revisited, we should open a bug and discuss it on the eml-dev list.

**Comment by cboettig** [comment]
@mbjones Good question.  I certainly can appreciate the perspective of those who want to keep EML markup not to burdensome to implement.  

However, personally I think TextType is in a challenging middle-ground, where it is complex enough that it's really not that easy to work with directly, while being too simple to be docbook compatible.  I just imagine more users would either prefer to use a text editor / word processor to write text with subscripts, emphasis and ordered lists, or just forgo their use entirely and write mostly plain text (with maybe a few section, para, and title markers.  I'd actually be curious what fraction of EML documents make use of inline markup elements like `<emphasis>`).  Figuring out how to give users an easy way to create such text without resorting to word processors seems like a challenge.  Even without pandoc it looks like there are a lot of tools for working with docbook (LibreOffice will export directly to docbook, and you're probably familiar with others).  

OTOH, changing the schema seems like a big ask.  I could see a case for actually making TextType simpler rather than more complex, but sounds like that discussion has already happened.  

For the time being at least, perhaps we just need an XSLT sheet or something that can go from docbook to TextType?  Or maybe there is a better alternative?

**Comment by cboettig** [comment]
Not sure how common / easy it will be for users who are creating text in Word to end up generating docbook that is outside of EML.  Ultimately some way to detect or at least document this would be nice, but can perhaps wait and see.  Other than possibly making the validator unhappy such cases will at least not throw any errors on the R end.
