### ISSUE TITLE
read_eml - slower to read & a class issue

### ISSUE THREAD

**Issue by lwasser** [ropensci/EML#138]
Hi @cboettig . 
I am reworking our EML lessons. 

The following code returns the warning below
```
    eml_HARV <- read_eml("http://harvardforest.fas.harvard.edu/data/eml/hf001.xml")
```

WARNING:
```
     Found more than one class "connection" in cache; using the first, from namespace 'EML'
     Found more than one class "connection" in cache; using the first, from namespace 'EML'
````
It seems to also be slower to load than it was previously (this may just be in my mind). Can you please explain what this warning means?
Thank you!

**Comment by cboettig** [comment]
hmm, I can't reproduce the warning at this time.  Can you start with a clean R session, load the library and run the read again and see?  That may be related to the slowness you see as well.  

(Installing from source results in a lot of stuff clogging up the cache with the S4 classes for some reason).  The functions do take a little while to run on that EML file, which is I think a function of it's size.  (I'm hoping the xml2 library will one day make some of this a bit faster too). 

Overall, this is a large file and thus may be a bit slow to parse and serialize though.  Will try and improve performance at some point once more of the API is pinned down.  



Good question about speed.

**Comment by lwasser** [comment]
Ok - i did a reboot and it imports now without that error. Thank you, Carl. I'll close this issue for now!
