### ISSUE TITLE
Feedback wanted on 'Creating EML' vignette

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#145]
Rendered vignette over on gh-pages branch: http://ropensci.github.io/EML/creating-EML.html.  Source in `vignettes/` dir of the repository.

This shows the use of most of the current methods, including creating an attributeList from a `data.frame` using `set_attributes()`, creating simple elements with the `new()` methods, reading in a `.docx` or `.md` for long text fields, and coercing R's `person` types.  Looking for feedback on all levels, including:

- Is this at all readable? Where are the descriptions too technical or too vague?
- Naming conventions.  Are the function and variable names reasonable?  (Mostly these try to stick with EML names, but not perfect).

- Design of the helper functions.  I've created helper functions for `set_coverage()`, `set_methods()`, and `set_physical()`.  The vignette shows pretty basic usage of all of these, though if you look at the package documentation you'll see that these include extra options not shown here.  (For instance, `set_physical()` includes arguments for most of the `TextFormat` types, while users wanting to define a different format currently have to construct it manually with `new()`.  My goal here has been to avoid the need to write really deeply nested `new()` constructor functions, since I think it can be difficult with those to easily figure out what's what.  

- What else is missing?

**Comment by lwasser** [comment]
HI @cboettig . am i doing something wrong? when i click on that link i get a blank screen. user error?

**Comment by cboettig** [comment]
@lwasser whoops, my bad.  Should be fixed now (though you may need to remove browser cache.  sidebar: a pity there's no natural way to commit HTML-compiled vignettes for R packages on GitHub; I've just compiled the Rmd and stuck it on the gh-pages branch.  I had accidentally committed the RStudio preview file instead of the actual html output).

**Comment by cboettig** [comment]
@lwasser Would definitely be interested in working on a spatial module vignette with you.  That would probably help surface some cases where we want to write some dedicated helper `set_` or `get_` methods, vs where the low-level methods are easy enough.

**Comment by lwasser** [comment]
Ok wonderful. When I am back from my trip I will dig into this vignette further and will start on a spatial file!

**Comment by ivanhanigan** [comment]
Re 'is that all readable':

On line https://github.com/ropensci/EML/blame/master/vignettes/creating-EML.Rmd#L138 you say 

"To make the code below more readable (aligning code and definitions side by side), we define these first as named character vectors, and convert that to a `data.frame`. (The `dplyr::frame_data` function also permits this more readable way to define data.frames inline)."


* But  In a previous case you did show this in that 'even more readable way' but I did not like it that much there either (see `dplyr::frame_data`: https://github.com/cboettig/eml2/blame/master/inst/examples/hf-205.R#L51)

* I prefer the base R version below, using `read.delim(textConnection(...))` because it does not depend on dplyr and is just as readable (IMHO). You can use any delimiter but I used `|` as this is common in other tables from `emacs/orgmode` or `kable` Also, older versions of dplyr fail on the call to `frame_data`, which happened to me the first time I tried that eml2 example above.

```r
attributes <-
read.delim(textConnection(
"attributeName | formatString |       definition |                                                attributeDefinition
       run.num |           NA | which run number |                 which run number (=block). Range: 1 - 6. (integer)
          year |         YYYY |               NA |                                                         year, 2012
           day |          DDD |               NA |                                      Julian day. Range: 170 - 209.
      hour.min |         hhmm |               NA |           hour and minute of observation. Range 1 - 2400 (integer)
        i.flag |           NA |               NA |           is variable Real, Interpolated or Bad (character/factor)
      variable |           NA |               NA | what variable being measured in what treatment (character/factor).
       value.i |           NA |               NA |       value of measured variable for run.num on year/day/hour.min.
"), sep = "|", strip.white = T)
```

And

```r
factors <-
read.delim(textConnection("
attributeName |       code |                                                                      definition
       i.flag |          R |                                                                            real
       i.flag |          I |                                                                    interpolated
       i.flag |          B |                                                                             bad
     variable |    control |                                                                   no prey added
     variable |        low |                                                    0.125 mg prey added ml-1 d-1
     variable |    med.low |                                                     0,25 mg prey added ml-1 d-1
     variable |   med.high |                                                      0.5 mg prey added ml-1 d-1
     variable |       high |                                                      1.0 mg prey added ml-1 d-1
     variable |   air.temp |                 air temperature measured just above all plants (1 thermocouple)
     variable | water.temp |                                  water temperature measured within each pitcher
     variable |        par | photosynthetic active radiation (PAR) measured just above all plants (1 sensor)
      value.i |    control |                                                              % dissolved oxygen
      value.i |        low |                                                              % dissolved oxygen
      value.i |    med.low |                                                              % dissolved oxygen
      value.i |   med.high |                                                              % dissolved oxygen
      value.i |       high |                                                              % dissolved oxygen
      value.i |   air.temp |                                                                       degrees C
      value.i | water.temp |                                                                       degrees C
      value.i |        par |                                                              micromoles m-1 s-1
"), sep = "|", strip.white = T)
```

**Comment by ivanhanigan** [comment]
I get this error:
https://github.com/ropensci/EML/blame/master/vignettes/creating-EML.Rmd#L286
```r
> methods_file <- system.file("examples/hf205-methods.docx", package = "EML")
> methods <- set_methods(methods_file)
pandoc: Cannot decode byte '\x8e': Data.Text.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream
Error: pandoc document conversion failed with error 1
#might be linux or other R differences?
> sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.5 LTS)

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] EML_1.0.0.0

loaded via a namespace (and not attached):
[1] compiler_3.2.4 magrittr_1.5   tools_3.2.4    roxygen2_4.1.0 Rcpp_0.12.3   
[6] stringi_0.4-1  stringr_1.0.0  devtools_1.7.0 XML_3.98-1.1  
```

Everything else worked as expected (removing methods from `dataset <- new("dataset",` let me complete the creation, validation and `eml_write` steps).

Looking good. I will have another read through of the text and comment on that next (ie you use the word slip twice in line https://github.com/ropensci/EML/blame/master/vignettes/creating-EML.Rmd#L77 but one of these could be 'insert'.  That kind of thing can always wait though, your code is working great.

PS 
https://github.com/ropensci/EML/blame/master/vignettes/creating-EML.Rmd#L213
'Sidebar': what does this mean?  Might be an idiom that does not translate from American to Australian English?

**Comment by cboettig** [comment]
@ivanhanigan thanks much!  re `dplyr:frame_data` good point, that's a bit obscure (and worse, has the error on older dplyr versions), so I think I should just drop that comment.  I won't mention `read_delim` explicitly (after all most users might not want to write out tables in `emacs`), but I think we can assume users can create tabular data in whatever method they like (e.g. some might just make this table in excel and read it in with `readxl` or `read.table()` etc).  

hmm, I'll have to investigate that parse error.  Can you see if you have `rmarkdown` installed and can run the examples in `rmarkdown::render()`?  I've set up the dependencies such that `rmardown` isn't required for EML, since it introduces `pandoc` as an external dependency, which can be a big nuisance (though if you use RStudio pandoc is pre-installed there).  `pandoc` is required for the conversion from `docx`.  Without `pandoc`, you can still define methods in `docbook` format (or plain text string I think?), which might be good for some users that can't or don't want to install pandoc and don't need to work with `docx` or markdown.  Still, if that's the cause, the package should at least throw a better error message instead of just failing like that.

**Comment by ivanhanigan** [comment]
Hey, I'm starting fresh on a VM and so will test all aspects of setting up a EML creation workflow.  First step is read the README.md, but I think this is an error, should it be `ropensci/EML`?
`r devtools::install_github("cboettig/EML")`
https://github.com/ropensci/EML/blame/master/README.md#L15

**Comment by ivanhanigan** [comment]
Do you prefer I make edits/comments in my clone and submit a PR?  if so would I use the master branch or one of the others?  or create a new branch?

**Comment by cboettig** [comment]
Yup, thanks

On Wed, Apr 20, 2016, 6:07 PM Ivan Hanigan <notifications@github.com> wrote:

> Hey, I'm starting fresh on a VM and so will test all aspects of setting up
> a EML creation workflow. First step is read the README.md, but I think this
> is an error, should it be ropensci/EML?
> r devtools::install_github("cboettig/EML")
> https://github.com/ropensci/EML/blame/master/README.md#L15
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/EML/issues/145#issuecomment-212678089>
>
-- 

http://carlboettiger.info

**Comment by cboettig** [comment]
A PR against master would be great.  Do fix it in the `README.Rmd` file and re-knit, rather than edit README.md.  Thanks

**Comment by ivanhanigan** [comment]
Hi, I've been at the Australian Ropensci Unconference all day (well, not really there, I am about 2000 kms away, but on slack channel).  I've got a complete (but invalid) minimal XML document for a dataset now.  The R script is in the README.md at https://github.com/swish-climate-impact-assessment/CTM_CSIRO_Sydney_Shipping_2010_2011/  Any comments would be great.  I might go thru the same steps with a dataTable format and a spatialVector format tomorrow before coming back and seeing why these XML validation rules are being broken. 
FYI the pandoc issue mentioned above.  I confirm that running Rstudio worked but from the terminal it did not.
Here is my version info (Ubuntu 12.04LTS):
```
$ pandoc --version
pandoc 1.12.4.2
Compiled with texmath 0.6.6.1, highlighting-kate 0.5.8.5.
```

**Comment by cgries** [comment]
After working through the vignette with my own data file I would recommend that you include a couple numeric columns in your example. That would shed some light on how to deal with unit and numberType. I realize that you have the vignette on units, but that doesn't really explain how to get the information into the EML file.

**Comment by cboettig** [comment]
I've added a basic example using a numberType unit (length in meters) to the vignette.  Let me know if that helps, or if more is needed.

**Comment by masalmon** [comment]
An example of how to add custom units to the eml might be nice to have too. The help of `set_unitList` does not show how to add it to the eml (in which slot + how).

**Comment by cboettig** [comment]
@masalmon good point, thanks.  I added a bit about how to add this to the eml in the help file now.  Also working on a vignette about units and custom units that should provide more information.

**Comment by masalmon** [comment]
Maybe you could add a sentence about the difference between `definition` and `attributeDefinition` in the vignette and the documentation of `set_attributes`, although one could deduce it from the example? 

Moreover, in the xlsx template, why is `attributeDefinition` further right than definition, while being useful more often? I have to confess I first used `definition` instead of `attributeDefinition` :smile: 

 I also wonder whether it should be compulsory to give an `attributeDefinition`, or at least whether not giving `attributeDefinition` should produce a warning.

**Comment by cboettig** [comment]
that's a good idea.  Though the behavior you suggest in #166 would also help address this, and might mean it makes more sense to leave the definition column out of the example (unless @mbjones talks us out of that).  

Re the xlsx template, the column order is more-or-less arbitrary, which is, admittedly not very helpful.  Having attribute, then attributeDefinition, and then groups by measurement scale (numerics, factors, etc) probably makes the most sense.  

I did actually put `attributeDefinition` to the far right because it is the usually the most verbose, and thus makes the rest of the table harder to read; particularly in the R console.  But not sure if that's really a good reason.
