### ISSUE TITLE
set_physical produces erroneous 'size' element

### ISSUE THREAD

**Issue by mbjones** [ropensci/EML#156]
Calling set_physical produces output for the size element that is invalid, like:

```XML
<size unit="bytes"/>
```

It should be:
```XML
<size unit="bytes">879</size>
```

**Comment by cboettig** [comment]
Nice catch, thanks

On Mon, May 9, 2016, 6:19 PM Matt Jones <notifications@github.com> wrote:

> Closed #156 <https://github.com/ropensci/EML/issues/156> via c958f94
> <https://github.com/ropensci/EML/commit/c958f944ad3f02d616c8ea5c338147b5f5716dfa>
> .
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/EML/issues/156#event-655161666>
>
-- 

http://carlboettiger.info
