### ISSUE TITLE
Why does set_unitList with as_metadata = TRUE return metadata and not additionalMetadata?

### ISSUE THREAD

**Issue by masalmon** [ropensci/EML#162]
This is what I currently do for creating an eml with custom unists:

```r
units <- read_csv2("eml/units.csv")
units <- set_unitList(units, as_metadata = TRUE)
units <- new("additionalMetadata", metadata = units)
eml <- new("eml",
           packageId = "27d5efb0-36da-11e6-9b72-739b6f659122",  # from uuid::UUIDgenerate(),
           system = "uuid", 
           dataset = dataset,
           additionalMetadata = units)
```

Are there cases when `units` would be useful as "metadata"? Otherwise, should set_unitLists directly output an "additionaMetadata" object?

**Comment by cboettig** [comment]
Good question, returning an `additionalMetadata` object directly might make more sense to save the extra typing.  In that case, perhaps we should also rename the argument from `as_metadata` to something else (maybe `as_additionalMetadata`)?  


In general I'm still figuring out the right balance of when helper functions should skip over levels.  There probably all cases where one would want to construct the `additionalMetadata` element more manually (maybe if also defining the optional `describes` field in `additionalMetadata`?  I don't fully understand the use pattern there, but @mbjones can probably weigh in), but in any event a user could still construct that with the low-level interface (e.g. starting with the `unitList` using `as_metadata = FALSE`.
