### ISSUE TITLE
Validate against data files / MetaDIG integration

### ISSUE THREAD

**Issue by maelle** [ropensci/EML#163]
I may have missed this: is there a way to validate the eml against the dataset, in particular to check whether all columns of each table have been documented as attributes?

**Comment by mbjones** [comment]
We're working on a metadata and data quality engine right now under our
MetaDIG project. That will definitely be one of its checks. More on that
soon!

Matt

**Comment by masalmon** [comment]
Will this be only for exported files or for local files as well?

**Comment by mbjones** [comment]
Its based on following pointers in the EML to the data files, which can be local or remote.

**Comment by cboettig** [comment]
closing this since I don't see anything actionable here, but re-open otherwise!

**Comment by mbjones** [comment]
For future reference, the MetaDIG project has a remote service being run through DataONE that can be used for metadata and data quality checks, but those same checks can be run locally in R through the [metadig-r](https://github.com/NCEAS/metadig-r) package, which is in development.
