### ISSUE TITLE
error with set_unitList example in vignette

### ISSUE THREAD

**Issue by cgries** [ropensci/EML#165]
@cboettig when I run your example for setting a custom unit I am getting this error:

Error in as(name, "xml_attribute") : 
  no method or default for coercing “factor” to “xml_attribute”

`unitType <- data.frame(id = c("jerk", "jerk"), dimension = c("length", "time"), power = c(1, -3) )`
`unit <- data.frame(id = "meterPerSecondCubed", unitType = "jerk")`
`unitList <- set_unitList(unit, unitType)`

Am I missing something?

**Comment by cboettig** [comment]
Can you reinstall the package  from github and then try again ?

**Comment by cgries** [comment]
I did now (guess missed that last night, sorry). Your example now works great. 

But trying to do this in my code 
`unitType <- data.frame(id = c("amountOfSubstanceAreaFlux", "amountOfSubstanceAreaFlux", "amountOfSubstanceAreaFlux"), dimension = c("amount", "area", "time"), power = c(0.000001, 1, 1) )`
`custom_units <- data.frame(id = c("micromolesPerSquareMeterPerSecond"), unitType = c("amountOfSubstanceAreaFlux"), parentSI = c("molesPerMeterSquaredPerSecond"), multiplierToSI = c(0.000001), description = c("photosynthetic active radiation"))`
`custom_units <- set_unitList(custom_units, unitType)`

I needed to turn the custom_units data frame into lists to avoid this error:

`Error in as.list.default(X) : no method for coercing this S4 class to a vector`

Now the `unitList` looks beautiful. But I am not sure how my code differs from yours other than that I am defining more parameters for the unit?

**Comment by cboettig** [comment]
@cgries 

Your example works just fine for me:

```r
unitType <- data.frame(id = c("amountOfSubstanceAreaFlux", "amountOfSubstanceAreaFlux", "amountOfSubstanceAreaFlux"), dimension = c("amount", "area", "time"), power = c(0.000001, 1, 1) )

custom_units <- data.frame(id = c("micromolesPerSquareMeterPerSecond"), unitType = c("amountOfSubstanceAreaFlux"), parentSI = c("molesPerMeterSquaredPerSecond"), multiplierToSI = c(0.000001), description = c("photosynthetic active radiation"))

unitList <- set_unitList(custom_units, unitType)

```

Note that you were overwriting the return value of the last line, `set_unitList`, to the variable `custom_units`, so what was once the `data.frame` custom unit became the S4 unitList object of that name, so running the `set_unitList` command a second time does indeed give the error you report.

**Comment by cgries** [comment]
@cboettig thanks, now it works just like your example. Not sure why I reassigned the variable.
