### ISSUE TITLE
Dealing with dateTimes: when dates are defined over multiple columns

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#17]
I think that the `dateTime` of a single observation should always be given in a single column. For reasons unfathomable to me, [some data](http://harvardforest.fas.harvard.edu:8080/exist/xquery/data.xq?id=hf205) represents year as a column, month as another column, day as another column, etc.

This is really only a problem when we do not have good metadata to recognize that these all refer to the same observation.  For instance, in the dataset linked above, we can tell that all the columns are "dateTime" objects, but we have generally no way to be sure that the "year" in column 2 is the year that corresponds to the "day" in column 3.  These could be independent dateTime observations, such as the start time and end time of a study, etc.

While it seems obvious that a single observation should get a single cell, apparently it isn't.  I'm open to ideas on how to approach these issues. 

This is a problem for `read_eml` for two reasons:

1. If we are to render any of these as time (`POSIXt` class) objects, we need to be able to associate them. A crude `as.POSIXt` would instead render the date as the current year, rather than that given in the column.  

2. Presumably a researcher would like to access the individual points in time, so ideally we would provide a combined column as date-time format, even if we return the original columns unformatted.  

### Questions

- Perhaps in such cases we leave the objects as character strings and go on? 

- When can we safely convert a dateTime object from a character string to a time object, and what class of time object should we use?  e.g. POSIXt, or objects from the [chron](http://cran.r-project.org/web/packages/chron/index.html) or [date](http://cran.r-project.org/web/packages/date/) packages?

**Comment by ivanhanigan** [comment]
Hi mate, I think, as you commented in #134: the "aim at just writing the EML for the data it is given without any fuss over best practices issues."
(and #126) such issues are beyond the scope of EML package which should just let you try your best..

**Comment by cboettig** [comment]
Yup, right on.
