### ISSUE TITLE
More user-friendly validation checks at R object creation level

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#178]
See discussion in this thread: https://github.com/ropensci/EML/issues/161

**Comment by maelle** [comment]
what are the steps needed for this? I'm interested in helping since I'd like to check my EML files :smile:

**Comment by maelle** [comment]
I also wonder if it'd be possible to document how to automatically create the min/max value for numeric variables. Not sure they're really useful. Moreover, this might be a suggestion closer to [this issue](https://github.com/ropensci/EML/issues/150)

**Comment by mbjones** [comment]
@maelle I don't think the `bounds` for numeric variables can be created automatically.  The `bounds` represent the minimum and maximum *allowable* value for a quantity, and do not represent the observed range in a data set.  So, for example, for a value expressed as a dimensionless percentage, the bounds are 0 to 100 inclusive.  If you tried to find that from the observed values in a data set, one might include that the min and max were 78 to 92, or whatever the observed values in that data set were.  The point of asking the user for `bounds` is to explicitly define the constraints on the domain of values, and only the person who is interpreting the type of measurement knows that. Once it is defined, then `bounds`  can be used to do quality checking to be sure all values within the data set are within the defined bounds.
