### ISSUE TITLE
get TextType tests to run without error on appveyor

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#179]
see #175 discussion

**Comment by maelle** [comment]
Now that I added the pandoc installation instructions in the appveyor yml file, does it work?

**Comment by cboettig** [comment]
@maelle For a moment it looked like this was working with the new appveyor configuration, but now appveyor seems to be failing entirely, seems not to be able to load pandoc?  e.g. https://ci.appveyor.com/project/cboettig/eml/build/1.0.67#L208, 

```
$env:Path += ";C:\Program Files (x86)\Pandoc\"
pandoc -v
'pandoc' is not recognized as an internal or external command,
operable program or batch file.
Command exited with code 1
```

Any ideas?

**Comment by cboettig** [comment]
okay, seem to have it passing now (dropped the caching of pandoc, which is also what @jennybc has currently in https://github.com/jennybc/reprex/blob/master/appveyor.yml ).  Closing :crossed_fingers:

**Comment by maelle** [comment]
@cboettig this is awesome! So thankful for Jenny's sharing her experience in that issue
