### ISSUE TITLE
Translating factors using eml

### ISSUE THREAD

**Issue by maelle** [ropensci/EML#184]
Here is the code I've mentioned in https://github.com/ropensci/EML/issues/183

https://github.com/masalmon/eml.tools 

The only function currently only works for a single table only. As I said I'm not sure whether this will be useful for other people. :-)

**Comment by maelle** [comment]
I have made good progress in my [one-function package](https://github.com/maelle/eml.tools). It now works for a dataset with several tables (which is my use case). I might add function to the package depending on our needs at work / on other suggestions. I guess I should close the issue but would it be worth it to mention this package/function in the documentation of `EML` in case it can be useful for someone else?

**Comment by cboettig** [comment]
Very cool, looks like a great example, certainly worth updating the docs to point people to, thanks!

**Comment by maelle** [comment]
Well thank _you_ for `EML`!
