### ISSUE TITLE
eml_validate fails with an eml-2.1.0 version document

### ISSUE THREAD

**Issue by mbjones** [ropensci/EML#185]
Validation fails to find the eml-2.1.0 schema when given a 2.1.0 document to validate.  Provide the ability to validate against all released versions of EML:

- [x] EML 2.1.1 
- [x] EML 2.1.0

**Comment by mbjones** [comment]
Validation against 2.1.1 and 2.1.0 is now working.

Validation against older versions fails, because those schemas are not deterministic -- this was a well-known bug in EML that was fixed with the EML 2.1.0 release.  Basically, the schema definition of the `additionalMetadata` field is not deterministic, preventing the schema from loading in modern schema validating parsers (historical parsers ignored this problem, which is how the bug was introduced in the schema).  The bottom line, I don't think we can validate 2.0.0 and 2.0.1 with any modern XML parser, so the best choice is to put an error message in to that effect.

**Comment by mbjones** [comment]
Decided that validating EML 2.0.0 and 2.0.1 was not possible because the schema is not deterministic.  But now both EML 2.1.0 and 2.1.1 can be validated properly, and a test framework is in place to add additional versions as they are released.  Finished changes.  @cboettig please review.

**Comment by cboettig** [comment]
Very nice, thanks!
