### ISSUE TITLE
naming functions

### ISSUE THREAD

**Issue by masalmon** [ropensci/EML#193]
I've just noticed there's `eml_get`, `eml_view` but `read_eml`, should some functions be renamed? I'd vote for `eml_something` because of tab auto-completion in RStudio.

**Comment by cboettig** [comment]
`read_eml` and `write_eml` are backwards on purpose,  to parallel base R & tidyverse read/write fns.  All other fns should start with `eml`.  Hadley does the same thing in xml2 names: https://github.com/hadley/xml2/blob/master/NAMESPACE

**Comment by masalmon** [comment]
Ok that makes sense thanks for the explanation!
