### ISSUE TITLE
Implement object-oriented methods for low level interface

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#197]
we should really be doing this in the standard S4 methods way rather than writing functions like `set_object` and `get_object`.  In most S4-based packages, users never call `new("individualName", givenName = "bob")`, but instead would create it with an initialize method whose name matches the object.  

```r
mbjones <- individualName(givenName = "Matt")
```

Likewise instead of a `get_` method, one would access slots with an accessor method based on the slot name:

```r
givenName(mbjones) # returns Matt
```

And similarly one would have assignment method, to assign a blank slot after initialization or to change a slot value:

```r
givenName(mbjones) <- "Matt"
surName(mbjones) <- "Jones"
```

The main reason I haven't done this is that it's simply a lot of writing -- there's 680 classes created in `classes.R`.  

@gmbecker mentioned to me that he had been working on an S4 Coffee package that could generate these standard methods from the classes themselves, but I'm not sure it's out yet.  Automatically generating all these methods for all the classes would at least mean you should get he autocomplete and the help docs, which would be a big win.  Also following the S4 standard approach here should make the whole thing more intuitive at least to users familiar with S4 or other more object-oriented design (though I think most R users tend towards a function-driven design and focus on verbs like `set_` `get_`, rather than nouns, so I dunno.  Trying to remember some very good suggestions from @richfitz in this regard).

**Comment by gmbecker** [comment]
FYI, I'm currently in the "documenting in preparation for submission for release" for an initial public release of S4Coffee, which will have the functionality you need to generate accessors for your classes automatically. I expect (but can't guarantee since that's how this works) that release will be a formality and in a couple week's time it will be in your hands and up on github.

**Comment by cboettig** [comment]
@gmbecker Thanks! Do ping us whenever it's out; we're looking forward to it.

**Comment by cboettig** [comment]
No longer necessary as EML is entirely S3 based now!
