### ISSUE TITLE
Improve handling of units & conversions for automating integration of data tables.

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#200]

**Comment by cboettig** [comment]
Wow, check out https://github.com/edzer/units !  Even supports automatic conversion & coercions of units when performing calculations, way slicker then pure `udunits2` alone (which already provides a nice conversion library).

**Comment by maelle** [comment]
I had started thinking about this (but done nothing) for `eml.tools` https://github.com/maelle/eml.tools/issues/3 

I guess `units` could be useful for creation but also later for use of a data set associated with an EML?

**Comment by cboettig** [comment]
Right.  

It might be nice to be able generate `unit` class objects (e.g. a numeric with units associated to it) from reading in a data.frame with metadata associated with it that declares the unit, and vice versa. (Haven't actually played with the `unit` package, so not sure how nicely it plays along as a column of a data.frame rather than it's own object, but I think it should be ok.  

My idealized use-case is to show how EML could streamline synthesizing multiple datasets that use different units into a single dataset automatically.

**Comment by maelle** [comment]
Another use case would be to show units appearing automatically on plots.

**Comment by cboettig** [comment]
much of this is now included `get_unit_id()`
