### ISSUE TITLE
EML fails under R 3.3.3

### ISSUE THREAD

**Issue by mbjones** [ropensci/EML#202]
Report from Steven Earl:

```
I had updated to R 3.3.3 (Another Canoe) this morning and noticed straightaway a problem with the EML package (see simplified code snippet and error message below).

> new('citation',
+                title = 'some title',
+                creator = c(creators),
+                pubDate = '2012')
Error in .Primitive("c")("some title") : 
  could not find symbol "recursive" in environment of the generic function

I downgraded to 3.3.2 (Sincere Pumpkin Patch), and all was right with the world again. I am running Ubuntu 16.04.
```

@cboettig responded: 'looks like this is the second time they've changed the signature of the concatenate method, `c()` in base R.  Arg; we can update the signature we're defining, but I think this is gonna make things hard to retain backwards compatibility on'

**Comment by cboettig** [comment]
hmm, I can't reproduce this error on 3.3.3.  `creators` is undefined in the example above, but if I do:

```r
creator <- new("creator")
creator@individualName <- c(new("individualName", surName = "Boettiger"))

new('citation',
     title = 'some title',
     creator = c(creator),
     pubDate = '2012')
```

I do not get an error.   


I do see the `c` method definition/documentation has changed in R 3.3.3, but we're not getting any warning about the documentation, so not clear if we have a problem here or not.  Maybe I need to follow up with Steven directly...

**Comment by amoeba** [comment]
I can reproduce it just fine on our copy of RStudio Server that's running 3.3.3:

```r
> library(EML)
> devtools::session_info()
Session info -------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.3 (2017-03-06)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2017-03-21                  

Packages -----------------------------------------------------------------------------------------------------------------
 package    * version  date       source         
 devtools     1.12.0   2016-06-24 CRAN (R 3.3.1) 
 digest       0.6.12   2017-01-27 cran (@0.6.12) 
 EML        * 1.0.1    2016-12-20 CRAN (R 3.3.2) 
 magrittr     1.5      2014-11-22 CRAN (R 3.3.0) 
 memoise      1.0.0    2016-01-29 CRAN (R 3.3.0) 
 rstudioapi   0.6      2016-06-27 CRAN (R 3.3.1) 
 stringi      1.1.2    2016-10-01 cran (@1.1.2)  
 stringr      1.1.0    2016-08-19 CRAN (R 3.3.1) 
 withr        1.0.2    2016-06-20 CRAN (R 3.3.1) 
 XML          3.98-1.5 2016-11-10 cran (@3.98-1.)
> creator <- new("creator")
> creator@individualName <- c(new("individualName", surName = "Boettiger"))
Error in c(new("individualName", surName = "Boettiger")) : 
  could not find symbol "recursive" in environment of the generic function
> new('citation',
+     title = 'some title',
+     creator = c(creator),
+     pubDate = '2012')
Error in .Primitive("c")("some title") : 
  could not find symbol "recursive" in environment of the generic function
```

I'll try in a container now. What environment are you on that you're not seeing this?

**Comment by amoeba** [comment]
Okay, so no errors when running that in a container using `rocker/rstudio`. The only difference I see is the version of R that `devtools::session_info()` reports for the EML package.

In a Docker container running `rocker/rstudio`, I get no errors and here's the EML line from `devtools::session_info()`:
```
EML      * 1.0.1    2016-12-20 CRAN (R 3.3.3)
```


On our NCEAS RStudio instance, I *do* get errors and here's the EML line from `devtools::session_info()`:
```
EML        * 1.0.1    2016-12-20 CRAN (R 3.3.2)
```

However, I can't figure out how to get the copy on our RStudio to report R 3.3.3. I've removed and re-installed with no change.

**Comment by amoeba** [comment]
After seeing a [this](https://twitter.com/henrikbengtsson/status/844347599876325376) thread on Twitter which linked to [this](https://stat.ethz.ch/pipermail/bioc-devel/2017-March/010559.html) mailing list page I'm thinking I just need to learn how to re-install packages. Not sure why I'm having a hard time on this RStudio server instance.

I think this Issue can be closed.

**Comment by srearl** [comment]
Thank you @cboettig and @amoeba - reinstalling EML after upgrading to 3.3.3 fixed the problem.

**Comment by cboettig** [comment]
Great!
