### ISSUE TITLE
eml_validate as condition for write_eml in the vignette about writing EML?

### ISSUE THREAD

**Issue by maelle** [ropensci/EML#208]
I'm now using

```r
validation <- eml_validate(eml, encoding = "latin1")
if(validation){
  print("The EML is valid, now saving it.")
  write_eml(eml, "personal_DB_eml.xml")
}else{
  print("The EML isn't valid yet, try again.")
  print(validation)
}


```
at work. Is it an useful example to add in the vignette about writing EML?

**Comment by cboettig** [comment]
Hey @maelle , I think you have to jog my memory now -- do you still need this extra validation wrapping to handle validating EML with non-ascii characters on Windows or did we fix this with the recent edits?

**Comment by maelle** [comment]
What do you mean by extra wrapping? This example above was just an example for the documentation. Reg. the encoding argument I _think_ I use it everywhere now (I'm not in the office so can't check)

**Comment by cboettig** [comment]
Ah, I think I was misreading the example earlier; but seems the user shouldn't have to write all that each time.  Based on your suggestion, it sounds like we ought to call `eml_validate` by default on any call to `eml_write`, and maybe issue a warning message if the file is not valid?  (I imagine we'd still want a way to opt out of this behavior, e.g. in cases where a user is writing lots of EML files automatically and validation just slows them down).  

re encoding, sounds like validation now works for you as long as you give the "latin1" encoding argument to `eml_validate` but not to `eml_write()`?  That seems pretty confusing to me, and presumably to other users; (One would think you'd want to specify the encoding on both `write` and validate`).  

Also, just to set me straight: is `latin1` the usual encoding to use on Windows for files with non-ascii characters? (e.g. what the mac/linux world would call UTF-8?)

**Comment by maelle** [comment]
* I don't think it should be default either, but in the documentation somewhere we might advise to validate before writing? Or will users expect that their EML is correct just because it could be saved? We should ask "naive" users if we find some.

* I'll check where I use the argument at work, I think I use it for both writing and validating so my example might be wrong although I thought I had copy-pasted from code I actually used. So much reproducibility 🤔 

* I have no idea actually, `latin1` worked so I didn't look further.

**Comment by maelle** [comment]
I checked, we really write EML without encoding arguments. Weird.
