### ISSUE TITLE
Check for factors in set_attributes

### ISSUE THREAD

**Issue by maelle** [ropensci/EML#210]
I'll soon make a PR with checks of the factors data.frame in `set_attributes`:

* like the attributes data.frame it has required fields.

* here we experienced issues with some attributeNames that had duplicate codes so I'm adding a check for that. cc @carlesmila

**Comment by maelle** [comment]
Note: it's very ugly code :-(

**Comment by cboettig** [comment]
Thanks!  I think this is closed by merging #211
