### ISSUE TITLE
Interesting change in behavior from XML to xml2 version of the package

### ISSUE THREAD

**Issue by amoeba** [ropensci/EML#212]
A user handed me a schema-invalid XML document they were having some trouble with while using the `xml2` version of the package. Their environment is R 3.3.2, EML 1.0.2.1.

Here's a minimal document:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<eml:eml xmlns:eml="eml://ecoinformatics.org/eml-2.1.1" 
         xmlns:stmml="http://www.xml-cml.org/schema/stmml-1.1" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         packageId="test" 
         system="test" 
         xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 eml.xsd">
  <additionalMetadata>
    <unitList>
      <unit id="test" name="test" parentSI="test" unitType="test" multiplierToSI="1">
        <description>some unit description</description>
      </unit>
    </unitList>
  </additionalMetadata>
</eml:eml>

```

Note the lack of enclosing `metadata` element around the `unitList`.

```r
> (doc <- read_eml("~/Downloads/salmon_exvessel.xml"))
<eml packageId="test" system="test" xsi:schemaLocation="eml://ecoinformatics.org/eml-2.1.1 eml.xsd">
  <additionalMetadata>some unit description</additionalMetadata>
</eml>
```

Is this odd behavior anything to worry about? I don't know what the behavior should be when reading schema-invalid documents. Could we pre-validate before reading in documents or should the user just fend for themselves?

If you try to read this document with the CRAN release (based on XML), you can't even do it:

```r
> (doc <- read_eml("~/Downloads/salmon_exvessel.xml"))
Error in metaclasses[[s]] : 
  attempt to select less than one element in get1index
```

**Comment by cboettig** [comment]
Hmm, if the R package is generating EML that's invalid like that, that's something to worry about -- I do remember such a problem, but I thought I had fixed it.

In general I don't think it's a problem that we don't throw an error if a document is invalid, but it's suspicious that an error isn't unavoidable since that pattern shouldn't match the corresponding S4 class.

**Comment by amoeba** [comment]
>  I do remember such a problem, but I thought I had fixed it.

It appears you did. I updated the user to the current `master` and the issue went away.

**Comment by cboettig** [comment]
:rocket:
