### ISSUE TITLE
Should set_physical do more for the user automatically?

### ISSUE THREAD

**Issue by amoeba** [ropensci/EML#220]
I was running through the Creating EML vignette with some example data and ran this:

```r
> data("iris")
> write.csv(iris, row.names = FALSE, "iris.csv")
> physical <- set_physical("iris.csv")
> physical
<physical system="uuid">
  <objectName>iris.csv</objectName>
  <size unit="bytes"/>
  <dataFormat>
    <textFormat>
      <recordDelimiter>\n\r</recordDelimiter>
      <attributeOrientation>column</attributeOrientation>
      <simpleDelimited>
        <fieldDelimiter>,</fieldDelimiter>
      </simpleDelimited>
    </textFormat>
  </dataFormat>
</physical>
```

And was pleased to find that the record and field delimiters were set but noted some things:

- The `size` field is created but empty
- No checksum was included

Presumably, the way to get the information into my `physical` object would be to specify it via the arguments to `set_physical`. But could/should `set_physical` do the above two things for the user automatically?

I'd be happy to PR.

**Comment by cboettig** [comment]
cool, yup, I think it makes sense to include these things automatically.  a PR would be great.

**Comment by amoeba** [comment]
Great, will do.

**Comment by amoeba** [comment]
All done. Let me know if that looks okay!

**Comment by cboettig** [comment]
looks like we never closed this.
