### ISSUE TITLE
Feature request: a utility to convert eml to roxygen tags + back again

### ISSUE THREAD

**Issue by jsta** [ropensci/EML#224]
I am doing some hand conversion between eml and roxygen tags and would love a utility to automate the process. The only package I have found which generates roxygen tags from a template is: https://github.com/metrumresearchgroup/sinew

**Comment by amoeba** [comment]
Interesting. What does this look like? Do you have an example EML and the roxygen markup you convert it to?

**Comment by maelle** [comment]
Is it for documenting data in your R packages?

**Comment by jsta** [comment]
@maelle Yes

**Comment by maelle** [comment]
Do you think the inverse use case (from roxygen tags to EML) would happen a lot?

**Comment by jsta** [comment]
@amoeba Unfortunately I do not have a one-to-one mapping example of going between the two formats at this time. Work is in progress. My colleagues and I are working off a minimally structured (non-EML, non-roxygen) metadata document. They are hand converting to EML. I am hand converting to roxygen. Would be a lot more efficient if that conversion only had to happen once.

**Comment by cboettig** [comment]
hmm... new version of EML has `set_software()` to create EML software description.  It uses a codemeta file as input (which can be created for an R package easily with the `codemetar` package).
