### ISSUE TITLE
Auto-detect recordDelimiter (and more?) in set_physical

### ISSUE THREAD

**Issue by amoeba** [ropensci/EML#236]
The package currently defaults to assuming CRLF which is only found on Windows (UNIX, modern macOS uses LF). This is a great default given the user base of the EML package but we can certainly do better. I'm filing this issue so I can come back to it and make this happen.

I envision turning the current impl:

```r
set_physical <- function(...,
                         recordDelimiter = "\\r\\n",
                         ...)

```

into at least:

```r
set_physical <- function(...,
                         recordDelimiter = detect_delim(objectName),
                         ...)

```

and possible more. The current implementation assumes simple CSVs. We might be able to do better without being wrong too often.

Something like this might be a start, though I dislike the `stringr` depenency but I seriously have no idea how to use regexes in base R:

```r
detect_delim <- function(path, nchars = 1e3) {
  # readChar() will error on non-character data so
  chars <- tryCatch({
    readChar(path, nchars)
  },
  error = function(e) {
    NA
  })

  ending <- stringr::str_extract(chars, "[\\r\\n]+")

  if (!is.na(ending)) {
    return(ending)
  }

  "\r\n"
}
```

**Comment by cboettig** [comment]
@amoeba this looks like a great idea, want to send a PR against `set_physical.R` (now that `eml2` is merged back here trying to catch up on outstanding issues ahead of the imminent 2.2.0 release!)

**Comment by amoeba** [comment]
Sounds good.
