### ISSUE TITLE
read_eml removes text when text formatting is used

### ISSUE THREAD

**Issue by isteves** [ropensci/EML#242]
When text formatting is used (`<superscript>`, `<emphasis>`, etc.), `read_eml` removes text around the text formatting, as shown below:

```
EML::read_eml("<abstract>
  <para>something
    <superscript>2</superscript>
  </para>
</abstract>")

#> <abstract>
#>   <para>
#>     <superscript>2</superscript>
#>   </para>
#> </abstract>
```

Using a `<section>` tag inside of `<abstract>` fixes this problem, but the `set_TextType` function does not do this:

```
f <- system.file("examples/hf205-abstract.docx", package = "EML")
a <- set_TextType(f)
as(a, "abstract")
```

I think it has something to do with the way `xml_to_s4` works, but I'm not sure which part of the problem needs to be fixed.  Happy to help with fixing if I can!

**Comment by cboettig** [comment]
@isteves Thanks, I'll take a look.  Can you also test this out in `eml2`: https://github.com/cboettig/eml2 ? `eml2` should overall be much easier to use than this `EML` package, and I think has much cleaner handling of text types in general.

**Comment by isteves** [comment]
Hi @cboettig, in trying `eml2` out, I'm having trouble figuring out how `eml_validate` works.  This workflow is something that works with `EML` but throws an error with `eml2`:

```
f <- system.file("extdata", "example.xml", package = "emld")
eml <- eml2::read_eml(f)
eml2::eml_validate(eml)

#> Error in xml2::xml_attr(eml, "schemaLocation") : object 'doc' not found
#> Error in UseMethod("read_xml") : 
#>  no applicable method for 'read_xml' applied to an object of class "NULL"
```

For context, I'm trying to test out text types this way:

```
f <- system.file("extdata", "example.xml", package = "emld")
eml <- eml2::read_eml(f)

# try reading in text from within R
a <- eml2::set_TextType(text = "This is the abstrac<superscript>t</superscript>.")
eml$dataset$abstract <- a
eml2::eml_validate(eml)

# try reading in text from a local file
a <- eml2::set_TextType("/Users/datateam/Desktop/abstract.docx") # local file that contains bold/italicized/superscript text
eml$dataset$abstract <- a
eml2::eml_validate(eml)
```

**Comment by cboettig** [comment]
`eml_validate` currently only works on XML files, so you want to call `write_eml` first.  (Or if the file is already on disk like in your examples, don't read it in: just `eml_validate(f)`

we should probably fix that so you can call it directly on the `eml` object like in your example as well.

**Comment by isteves** [comment]
Ok, added `write_eml` in and both ways of adding textType work fine!

**Comment by cboettig** [comment]
resolved, and eml2 merged back here now so closing.
