### ISSUE TITLE
set_TextType on windows machine

### ISSUE THREAD

**Issue by scelmendorf** [ropensci/EML#246]
I'm having trouble getting the set_TextType to work correctly on my PC. Comparing results to the same code on ubuntu, it seems that the problem is that xml2::read_xml on a PC adds a namespace to a word document (running through examples using the hf205-abstract.docx).

On windows:
f <- system.file("examples/hf205-abstract.docx", package = "EML")
> docbook<-to_docbook(f)
> xml2::xml_ns(docbook)
d1    <-> http://docbook.org/ns/docbook
xlink <-> http://www.w3.org/1999/xlink

Same commands on linux machine
> f <- system.file("examples/hf205-abstract.docx", package = "EML")
> docbook<-to_docbook(f)
> xml2::xml_ns(docbook)
 <-> 

It seems that one possible fix is explicitly check for namespaces within the set_para and set_section functions (or strip namespaces would also work?)

set_para=function(docbook) {
#para <- xml2::xml_find_all(docbook, "/article/para") # this is the problem line
#replace the line above with one that incorporates potential namespaces
  para <-   xml2::xml_find_all(docbook, "/article/para", ns=xml2::xml_ns(docbook))
  s <- lapply(para, function(x) new("para", list(x)))
  as(s, "ListOfpara")
}

I looked in the dev version of eml2 and didn't see it was fixed there, but it was a pretty cursory look...so perhaps I should be using that instead?
Thanks

**Comment by cboettig** [comment]
Thanks; yes, can you please test on eml2 as well?  Some text type issues are fixed there. If no dice, let me know your pandoc version too.

**Comment by scelmendorf** [comment]
Yes - it is fixed in eml2. Thanks! Though, in using eml2 I am now stuck on additionalMetadata to make custom units which doesn't seem to be working as expected. Do you happen to have a functioning example of that in eml2?
