### ISSUE TITLE
Reading and writing CSV files should have full implementation / translation of read.table API

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#29]
R's read.table() function (which read.csv is aliased to) provides lots of options that we should 
- [ ] be encoded in the metadata when we write csv
- [ ] be reading in from the metadata when we read csv

``` ruby
 read.table(file, header = FALSE, sep = "", quote = "\"'",
                dec = ".", row.names, col.names,
                as.is = !stringsAsFactors,
                na.strings = "NA", colClasses = NA, nrows = -1,
                skip = 0, check.names = TRUE, fill = !blank.lines.skip,
                strip.white = FALSE, blank.lines.skip = TRUE,
                comment.char = "#",
                allowEscapes = FALSE, flush = FALSE,
                stringsAsFactors = default.stringsAsFactors(),
                fileEncoding = "", encoding = "unknown", text)
```

See `?read.table` for details.  Particularly important for the read interface.

**Comment by cboettig** [comment]
Appropriate thing here would probably be a helper function to construct the `read.table` R options from the `<physical>` node documentation.

**Comment by ivanhanigan** [comment]
Hi mate, I think, as you commented in #134 (and #126) `such issues are beyond the scope of EML package which should just let you try your best.`.

**Comment by cboettig** [comment]
We cover creating most of these in `set_physical()` already (though just using the EML terms, not the R terms), so it probably would be reasonable to have a `get_physical()` that returns the options for `read.table()` (and maybe `readr":read_table()`)
