### ISSUE TITLE
Use pandoc conditionally

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#290]
As per email from CRAN:

> As 'Writing R Extensions' says
>> ' A package with a hard-to-satisfy system requirement is by definition
not portable, annoyingly so if this is not declared in the
‘SystemRequirements’ field.  The most common example is the use of
pandoc, which is only available for a very limited range of platforms
(and has onerous requirements to install from source) and has
capabilities that vary by build but are not documented.

>> Usage of external commands should always be conditional on a test for
existence (perhaps using Sys.which), as well as declared in the
‘SystemRequirements’ field.'

> Do ensure that your package is compliant before **Dec 17** to safely retain
it on CRAN.

**Comment by cboettig** [comment]
I'll just note that I don't really understand the issue.  We only use `pandoc` through a dependency on `rmarkdown` (which we already [use conditionally](https://github.com/ropensci/EML/blob/master/R/set_TextType.R#L90)).  `pandoc` is a listed dependency of `rmarkdown`, and is listed in the systemRequirements of the `rmarkdown` package.  

I would not think that a package would need to list the systemRequirements of its dependencies, any more than it needs list the dependencies of it's dependencies.  `rmarkdown` is a CRAN package and appears not to be included on the list of packages receiving this email.  

Anyway, I think we can easily add a condition that checks `rmarkdown::pandoc_available()` [here](https://github.com/ropensci/EML/blob/master/R/set_TextType.R#L90))...

**Comment by amoeba** [comment]
Odd. The language isn't really clear, do they mean `EML` depends on `pandoc` or are they merely giving it as an example? Is it possible that `xml2` is another example because it requires `libxml-dev`? `jq` is another one. Really, EML depends on `librdf0-dev`, `libv8-dev`, `libjq-dev`, and `libudunits2-dev` which (maybe?) they're saying reduces portability.

**Comment by cboettig** [comment]
Operationally, I believe they are referring to https://cran.r-project.org/web/checks/check_results_EML.html, where CRAN has several platforms they test on which lack pandoc (Solaris, though apparently all of the CRAN MacOS test servers also lack pandoc).

Note the rmarkdown package itself uses `skip_on_cran()` ....

**Comment by cboettig** [comment]
hopefully fixed in 9bb6e0c3ce24ec853055ec8948c7ba1c7b394674.  

Submitted patch to CRAN as v2.0.1 (bumped the NEWS file as well with the recent PRs since 2.0.0 release).   🤞🤞
