### ISSUE TITLE
Fix issues on CRAN by 2021-03-11

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#317]
https://cran.r-project.org/web/checks/check_results_EML.html

**Comment by mbjones** [comment]
@cboettig Bummer. It seems they deprecated `as.units` in https://github.com/r-quantities/units/pull/259 

And would moving to using the exported `units::as_units` (without the '.') fix the issue? Might be an easy fix.

**Comment by cboettig** [comment]
looks good, will give that a go.
