### ISSUE TITLE
Fix R CMD CHK on 3.x R versions

### ISSUE THREAD

**Issue by mbjones** [ropensci/EML#320]
We are seeing failures in the tests for older versions of R on ubuntu through CI tests because the suggested package `taxadb` is not available. The error is: `Error:   Package suggested but not available: ‘taxadb’`.

Discussing with @cboettig on slack, he said:

> taxadb is just a Suggested package, requiring R 4.x would be too much.  Uwe at CRAN suggested we switch `taxadb` from rappdirs to tools::R_user_dir() because it plays nicer with CRAN policies (but was only added to tools in R > 4.0)
>
> adding a check for skipping those checks on earlier R versions would be best I think

So, the proposal is to skip those checks for now on CRAN. Alternatively, we could switch to using `tools::R_user_dir()` but only if we are willing to increase our minimum version to R > 4.0.

**Comment by cboettig** [comment]
done in #321
