### ISSUE TITLE
potential use case in converting to long forms when combining data frames

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#51]
This issue is mostly note to myself in thinking out potential illustrative use cases.  no input really needed at this time, kinda trivial example here.  

What would eml look like to encode replicate models?  Can we easily convert metadata to additional column when combining data of matching column descriptions but differing metadata, e.g. 

---
model: Allen
parameters: r=1, K = 10, C = 5
nuisance parameters: sigma_g = 0.1
seed: 1234

---

value | density 
-------- | ------
0.0    |  0.12
0.1    |  0.14
0.2    |  0.22
0.3    |  0.4

And: 

---
model: Myers
parameters: r=1, K = 10, theta = 1
nuisance parameters: sigma_g = 0.1
seed: 1234

---

value | density 
-------- | ------
0.0    |  0.14
0.1    |  0.11
0.2    |  0.33
0.3    |  0.33

**Comment by ivanhanigan** [comment]
@cboettig I think this would look like one package for `Allen`, another for `Myers`, and a third for `combined`.  But if you're current streak of closing `EML::issues` is to continue unabated I'd recommend logging this particular idea in your notebook or somewhere else so the `github EML` package can launch onto `CRAN` asap.  Tell me if I am out of line here?

**Comment by cboettig** [comment]
right on.
