### ISSUE TITLE
Dealing with dates

### ISSUE THREAD

**Issue by cboettig** [ropensci/EML#78]
Date columns are somewhat problematic than they should be.  Several challenges exist here:

- [ ] the R user may represent dates as almost any type: integer, numeric, character, factor, or Date.  So detecting the format based on the column class isn't reliable.  (there may be good reasons of course to treat date as a factor for a given statistical test or plot, etc)
- [ ] R's Date type insists on a fully specified date-time object. So if a user has separate columns for year and day, we can't treat each as an date column independently.  
- [x] EML's date format does't use the ISO C99 / POSIX standard for `strftime`, for instance Julian days might be specified using the less explicit format string `DDD` rather than `%j`.  

current automated handling of dates based on column types can result in incorrect EML (see Advanced writing example).  Typing these as characters and explicitly declaring it as a date in the unit metadata.

**Comment by ivanhanigan** [comment]
I think you deal with dates as well as can be expected given the tricksy nature of the beast.  You van probably close this issue hey?

**Comment by cboettig** [comment]
Yup, right.  Meanwhile there's a good ecosystem for dealing with dates in general; e.g. `readr` package `read_csv()` does a much better job reading in dates, and lubridate for manipulating them.  But now that we're just focused on the metadata representation we aren't assuming the actual data table is even read into R anyway, so like you say these issues are now beyond the scope here.
