### ISSUE TITLE
Worth adding Shiny support?

### ISSUE THREAD

**Issue by karthik** [ropensci/EML#99]
In relation to the [wizard](https://github.com/ropensci/EML/blob/master/R/eml_wizards.R) wondering if it would be worth adding a Shiny module as an enhancement. It would allow users to document all the fields in a browser, often suggesting standard units. It also gets around the linear approach one has to work with on the command line.  
New version of Shiny can take input and send everything back to the kernel (not just for readonly use).

**Comment by ivanhanigan** [comment]
Hey, is this the same as #116?

**Comment by cboettig** [comment]
@ivanhanigan yup.
